const games = [
    {
        "id": 540,
        "title": "Overwatch 2",
        "thumbnail": "https://www.freetogame.com/g/540/thumbnail.jpg",
        "shortDescription": "A hero-focused first-person team shooter from Blizzard Entertainment.",
        "gameUrl": "https://www.freetogame.com/open/overwatch-2",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Activision Blizzard",
        "developer": "Blizzard Entertainment",
        "releaseDate": "2022-10-04",
        "freetogameProfileUrl": "https://www.freetogame.com/overwatch-2"
    },
    {
        "id": 517,
        "title": "Lost Ark",
        "thumbnail": "https://www.freetogame.com/g/517/thumbnail.jpg",
        "shortDescription": "Smilegate's free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.",
        "gameUrl": "https://www.freetogame.com/open/lost-ark",
        "genre": "ARPG",
        "platform": "PC (Windows)",
        "publisher": "Amazon Games",
        "developer": "Smilegate RPG",
        "releaseDate": "2022-02-11",
        "freetogameProfileUrl": "https://www.freetogame.com/lost-ark"
    },
    {
        "id": 516,
        "title": "PUBG: BATTLEGROUNDS",
        "thumbnail": "https://www.freetogame.com/g/516/thumbnail.jpg",
        "shortDescription": "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
        "gameUrl": "https://www.freetogame.com/open/pubg",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "KRAFTON, Inc.",
        "developer": "KRAFTON, Inc.",
        "releaseDate": "2022-01-12",
        "freetogameProfileUrl": "https://www.freetogame.com/pubg"
    },
    {
        "id": 508,
        "title": "Enlisted",
        "thumbnail": "https://www.freetogame.com/g/508/thumbnail.jpg",
        "shortDescription": "Get ready to command your own World War II military squad in Gaijin and Darkflow Software's MMO squad-based shooter Enlisted. ",
        "gameUrl": "https://www.freetogame.com/open/enlisted",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Gaijin Entertainment",
        "developer": "Darkflow Software",
        "releaseDate": "2021-04-08",
        "freetogameProfileUrl": "https://www.freetogame.com/enlisted"
    },
    {
        "id": 345,
        "title": "Forge of Empires",
        "thumbnail": "https://www.freetogame.com/g/345/thumbnail.jpg",
        "shortDescription": "A free to play 2D browser-based online strategy game, become the leader and raise your city.",
        "gameUrl": "https://www.freetogame.com/open/forge-of-empires",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "InnoGames",
        "developer": "InnoGames",
        "releaseDate": "2012-04-17",
        "freetogameProfileUrl": "https://www.freetogame.com/forge-of-empires"
    },
    {
        "id": 475,
        "title": "Genshin Impact",
        "thumbnail": "https://www.freetogame.com/g/475/thumbnail.jpg",
        "shortDescription": "If you've been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you're going to want to check out miHoYo's Genshin Impact.",
        "gameUrl": "https://www.freetogame.com/open/genshin-impact",
        "genre": "Action RPG",
        "platform": "PC (Windows)",
        "publisher": "miHoYo",
        "developer": "miHoYo",
        "releaseDate": "2020-09-28",
        "freetogameProfileUrl": "https://www.freetogame.com/genshin-impact"
    },
    {
        "id": 523,
        "title": "Fall Guys",
        "thumbnail": "https://www.freetogame.com/g/523/thumbnail.jpg",
        "shortDescription": "Play the most competitive massively multiplayer party royale game featuring beans ever for free on a variety of platforms. ",
        "gameUrl": "https://www.freetogame.com/open/fall-guys",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Mediatonic",
        "developer": "Mediatonic",
        "releaseDate": "2020-08-04",
        "freetogameProfileUrl": "https://www.freetogame.com/fall-guys"
    },
    {
        "id": 340,
        "title": "Game Of Thrones Winter Is Coming",
        "thumbnail": "https://www.freetogame.com/g/340/thumbnail.jpg",
        "shortDescription": "A free-to-play browser-based RTS based on the George R.R. Martin novels and popular HBO series.",
        "gameUrl": "https://www.freetogame.com/open/game-of-thrones-winter-is-coming",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "GTArcade",
        "developer": "YOOZOO Games ",
        "releaseDate": "2019-11-14",
        "freetogameProfileUrl": "https://www.freetogame.com/game-of-thrones-winter-is-coming"
    },
    {
        "id": 347,
        "title": "Elvenar",
        "thumbnail": "https://www.freetogame.com/g/347/thumbnail.jpg",
        "shortDescription": "A browser based city-building strategy MMO set in the fantasy world of Elvenar.",
        "gameUrl": "https://www.freetogame.com/open/elvenar",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "InnoGames",
        "developer": "InnoGames",
        "releaseDate": "2015-04-08",
        "freetogameProfileUrl": "https://www.freetogame.com/elvenar"
    },
    {
        "id": 11,
        "title": "Neverwinter",
        "thumbnail": "https://www.freetogame.com/g/11/thumbnail.jpg",
        "shortDescription": "A free-to-play 3D action MMORPG based on the acclaimed Dungeons & Dragons fantasy roleplaying game. ",
        "gameUrl": "https://www.freetogame.com/open/neverwinter",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Perfect World Entertainment",
        "developer": "Cryptic Studios",
        "releaseDate": "2013-12-06",
        "freetogameProfileUrl": "https://www.freetogame.com/neverwinter"
    },
    {
        "id": 380,
        "title": "Dark Orbit Reloaded",
        "thumbnail": "https://www.freetogame.com/g/380/thumbnail.jpg",
        "shortDescription": "A browser-based 3D space-combat MMO with a massive playerbase!",
        "gameUrl": "https://www.freetogame.com/open/darkorbit",
        "genre": "Shooter",
        "platform": "Web Browser",
        "publisher": "Bigpoint",
        "developer": "Bigpoint",
        "releaseDate": "2006-12-11",
        "freetogameProfileUrl": "https://www.freetogame.com/darkorbit"
    },
    {
        "id": 573,
        "title": "Titan Revenge",
        "thumbnail": "https://www.freetogame.com/g/573/thumbnail.jpg",
        "shortDescription": "A 3D Norse-themed browser MMORPG developed and published by Game Hollywood Games",
        "gameUrl": "https://www.freetogame.com/open/titan-revenge",
        "genre": "MMORPG",
        "platform": "Web Browser",
        "publisher": "Game Hollywood Games",
        "developer": "Game Hollywood Games",
        "releaseDate": "2023-12-20",
        "freetogameProfileUrl": "https://www.freetogame.com/titan-revenge"
    },
    {
        "id": 521,
        "title": "Diablo Immortal",
        "thumbnail": "https://www.freetogame.com/g/521/thumbnail.jpg",
        "shortDescription": "Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.",
        "gameUrl": "https://www.freetogame.com/open/diablo-immortal",
        "genre": "MMOARPG",
        "platform": "PC (Windows)",
        "publisher": "Blizzard Entertainment",
        "developer": "Blizzard Entertainment",
        "releaseDate": "2022-06-02",
        "freetogameProfileUrl": "https://www.freetogame.com/diablo-immortal"
    },
    {
        "id": 522,
        "title": "Flyff Universe",
        "thumbnail": "https://www.freetogame.com/g/522/thumbnail.jpg",
        "shortDescription": "Get the full Flyff experience on any platform with the free-to-play browser-based MMORPG Flyff Universe.",
        "gameUrl": "https://www.freetogame.com/open/flyff-universe",
        "genre": "MMORPG",
        "platform": "Web Browser",
        "publisher": "Gala Lab",
        "developer": "Gala Lab",
        "releaseDate": "2022-06-14",
        "freetogameProfileUrl": "https://www.freetogame.com/flyff-universe"
    },
    {
        "id": 511,
        "title": "Phantasy Star Online 2 New Genesis",
        "thumbnail": "https://www.freetogame.com/g/511/thumbnail.jpg",
        "shortDescription": "The legacy of Phantasy Star Online 2 continues a thousand years later!",
        "gameUrl": "https://www.freetogame.com/open/pso2-new-genesis",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Sega",
        "developer": "Sega",
        "releaseDate": "2021-06-09",
        "freetogameProfileUrl": "https://www.freetogame.com/pso2-new-genesis"
    },
    {
        "id": 455,
        "title": "Eternal Fury",
        "thumbnail": "https://www.freetogame.com/g/455/thumbnail.jpg",
        "shortDescription": "A free-to-play ARPG from R2 Games!",
        "gameUrl": "https://www.freetogame.com/open/eternal-fury",
        "genre": "MMORPG",
        "platform": "Web Browser",
        "publisher": "R2 Games",
        "developer": "R2 Games",
        "releaseDate": "2019-05-21",
        "freetogameProfileUrl": "https://www.freetogame.com/eternal-fury"
    },
    {
        "id": 5,
        "title": "Crossout",
        "thumbnail": "https://www.freetogame.com/g/5/thumbnail.jpg",
        "shortDescription": "A post-apocalyptic MMO vehicle combat game! ",
        "gameUrl": "https://www.freetogame.com/open/crossout",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Targem",
        "developer": "Gaijin",
        "releaseDate": "2017-05-30",
        "freetogameProfileUrl": "https://www.freetogame.com/crossout"
    },
    {
        "id": 9,
        "title": "World of Warships",
        "thumbnail": "https://www.freetogame.com/g/9/thumbnail.jpg",
        "shortDescription": "A 3D free to play naval action-themed MMO from the creators of World of Tanks! ",
        "gameUrl": "https://www.freetogame.com/open/world-of-warships",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Wargaming",
        "developer": "Wargaming",
        "releaseDate": "2015-07-02",
        "freetogameProfileUrl": "https://www.freetogame.com/world-of-warships"
    },
    {
        "id": 12,
        "title": "War Thunder",
        "thumbnail": "https://www.freetogame.com/g/12/thumbnail.jpg",
        "shortDescription": "A MMO shooter that puts you in command of hundreds of the finest combat vehicles of World War II.",
        "gameUrl": "https://www.freetogame.com/open/war-thunder",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Gaijin Entertainment",
        "developer": "Gaijin Entertainment",
        "releaseDate": "2013-08-15",
        "freetogameProfileUrl": "https://www.freetogame.com/war-thunder"
    },
    {
        "id": 2,
        "title": "World of Tanks",
        "thumbnail": "https://www.freetogame.com/g/2/thumbnail.jpg",
        "shortDescription": "If you like blowing up tanks, with a quick and intense game style you will love this game!",
        "gameUrl": "https://www.freetogame.com/open/world-of-tanks",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Wargaming",
        "developer": "Wargaming",
        "releaseDate": "2011-04-12",
        "freetogameProfileUrl": "https://www.freetogame.com/world-of-tanks"
    },
    {
        "id": 581,
        "title": "XDefiant",
        "thumbnail": "https://www.freetogame.com/g/581/thumbnail.jpg",
        "shortDescription": "A free-to-play first-person arena shooter from Ubisoft.",
        "gameUrl": "https://www.freetogame.com/open/xdefiant",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Ubisoft",
        "developer": "Ubisoft",
        "releaseDate": "2024-05-21",
        "freetogameProfileUrl": "https://www.freetogame.com/xdefiant"
    },
    {
        "id": 560,
        "title": "Palia",
        "thumbnail": "https://www.freetogame.com/g/560/thumbnail.jpg",
        "shortDescription": "A cozy MMO with homebuilding and some adventure.",
        "gameUrl": "https://www.freetogame.com/open/palia",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Singularity Six",
        "developer": "Singularity Six",
        "releaseDate": "2023-08-10",
        "freetogameProfileUrl": "https://www.freetogame.com/palia"
    }
];

import { GameCard } from "./GameCard";

export function GamesList() {
    return (
        <>
            {games.map(x => (<GameCard game={x} />))}
        </>
    )
}